export type Entity = {id: string; createdAt: string; updatedAt: string; version: number};
export type Goal = 'technique' | 'aerobic' | 'habit' | 'interval';
export type Experience = 'new' | 'basic' | 'regular';
export type Profile = Entity & {experience: Experience; goal: Goal; weeklyDays: number; availableMinutes: number; machine: string; timeZone: string; sound: boolean};
export type Stage = {id: string; kind: 'warmup' | 'work' | 'recovery' | 'cooldown'; durationSeconds: number; rpe: [number, number]; cue: string};
export type Course = {id: string; title: string; category: Goal | 'recovery'; description: string; suitability: string; level: 'new' | 'basic' | 'regular'; contentVersion: string; status: 'draft' | 'confirmed'; stages: Stage[]; plannedDurationSeconds: number; focus: string; alternativeId: string};
export type Draft = Entity & {course: Course; state: 'ready' | 'running' | 'paused' | 'suspended' | 'completed' | 'ended-early'; elapsedMs: number; startedAt: string; endedAt?: string; scheduledId?: string; owner: string; leaseUntil: number; revision: number};
export type Feedback = {rpe: number; discomfort: boolean; note: string; technique: 'stable' | 'practice'; feeling: 'good' | 'tired'; assessed?: boolean};
export type Metric = {value: number; unit: 'm' | 's/500m' | 'spm' | 'W' | 'kcal'; source: 'manual' | 'derived'; scope: 'whole-session'; formulaVersion?: string};
export type Workout = Entity & {sessionId: string; scheduledId?: string; title: string; startedAt: string; endedAt: string; completionStatus: 'completed' | 'ended-early'; captureSource: 'guided' | 'manual-entry'; activeDurationSeconds: number; workDurationSeconds: number; course?: Course; stageResults: {stageId: string; actualSeconds: number; status: 'completed' | 'partial' | 'skipped'}[]; metrics: Record<string, Metric | null>; feedback: Feedback};
export type LessonProgress = Entity & {viewedAt: string; contentVersion: string; selfChecks: boolean[]};
export type TrainingMode = 'aerobic' | 'anaerobic';
export type CustomSession = {warmupMinutes:number; cooldownMinutes:number; workSeconds:number; recoverySeconds:number; repeats:number};
export type PlanTraining = {mode:TrainingMode; weeks:number; weeklyDays:number; presetId?:string; custom?:CustomSession};
export type Plan = Entity & {templateId: string; title: string; startDate: string; week: number; status: 'active' | 'paused' | 'completed'; ruleVersion: string; templateVersion: string; reason: string; timeZone: string; training?:PlanTraining};
export type Scheduled = Entity & {planId: string; localDate: string; week: number; slot?:number; course: Course; status: 'planned' | 'skipped' | 'completed'; linkedSessionId?: string};
export type Snapshot = {schemaVersion: 2; revision: number; profile: Profile | null; lessons: LessonProgress[]; plans: Plan[]; scheduled: Scheduled[]; draft: Draft | null; workouts: Workout[]; lastBackupAt?: string};
export type Backup = {format: 'home-rower-backup'; exportVersion: 1; schemaVersion: 1 | 2; appVersion: string; contentVersion: string; exportedAt: string; counts: {workouts: number; scheduled: number; lessons: number; plans: number}; data: Snapshot};
export const APP_VERSION = '0.2.0';
export const CONTENT_VERSION = '1.0.0';
export const newEntity = (id: string = crypto.randomUUID()): Entity => {const now = new Date().toISOString(); return {id, createdAt: now, updatedAt: now, version: 1};};
export const emptySnapshot = (): Snapshot => ({schemaVersion: 2, revision: 0, profile: null, lessons: [], plans: [], scheduled: [], draft: null, workouts: []});
