import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {launch,appURL,dialog,useTemplate} from './ui-helpers.mjs';
const output='test-results/iphone-air';await fs.mkdir(output,{recursive:true});
if(!process.env.AIR_FOCUS_ONLY){const r=spawnSync(process.execPath,['tests/browser.mjs'],{env:{...process.env,DEVICE_PROFILE:'iphone-air'},encoding:'utf8'});process.stdout.write(r.stdout);process.stderr.write(r.stderr);assert.equal(r.status,0,'iPhone Air 核心功能流程');}
const browser=await launch(),context=await browser.newContext({viewport:{width:420,height:912},screen:{width:420,height:912},deviceScaleFactor:3,isMobile:true,hasTouch:true,colorScheme:'light'}),page=await context.newPage(),results=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));
const layout=async label=>{
  const issues=await page.evaluate(()=>{const issues=[];if(document.documentElement.scrollWidth>innerWidth+1)issues.push('document overflow');const active=[...document.querySelectorAll('dialog[open]')].at(-1)||document.querySelector('main');for(const e of active.querySelectorAll('button,input,select,summary,a')){const s=getComputedStyle(e),r=e.getBoundingClientRect();if(!r.width||!r.height||s.visibility==='hidden')continue;const t=e.matches('input[type=checkbox]')?e.closest('label'):e,rect=t.getBoundingClientRect();if(rect.height<43.5||rect.width<43.5)issues.push((e.getAttribute('aria-label')||e.textContent||e.tagName).trim().slice(0,30)+' target '+rect.width+'x'+rect.height);if(r.left<-1||r.right>innerWidth+1)issues.push(e.tagName+' outside width');}if(active.scrollWidth>active.clientWidth+1)issues.push('internal overflow');return issues;});assert.deepEqual(issues,[],label);
};
try{
  await page.goto(appURL,{waitUntil:'domcontentloaded'});await page.getByRole('heading',{name:'训练计划',exact:true}).waitFor();
  const actual=await page.evaluate(()=>({width:innerWidth,height:innerHeight,dpr:devicePixelRatio,touch:navigator.maxTouchPoints}));assert.ok(Math.abs(actual.dpr-3)<.0001);assert.deepEqual({...actual,dpr:3},{width:420,height:912,dpr:3,touch:1});await page.screenshot({path:output+'/templates-light.png'});const png=await fs.readFile(output+'/templates-light.png');assert.equal(png.readUInt32BE(16),1260);assert.equal(png.readUInt32BE(20),2736);results.push('420×912、DPR 3、触控、1260×2736 截图');
  await useTemplate(page,12,'基础耐力');
  const modes=[{name:'portrait',width:420,height:912,safe:{top:62,bottom:34}},{name:'browser-bars',width:420,height:760,safe:{}},{name:'landscape',width:912,height:420,safe:{left:62,right:62,bottom:21}},{name:'narrow',width:320,height:720,safe:{}},{name:'desktop',width:1200,height:900,safe:{}}];
  for(const mode of modes)for(const color of ['light','dark']){
    await page.setViewportSize({width:mode.width,height:mode.height});await page.evaluate(v=>{for(const side of ['top','bottom','left','right'])document.documentElement.style.setProperty('--safe-'+side,(v[side]||0)+'px');},mode.safe);
    await page.emulateMedia({colorScheme:color,reducedMotion:'reduce'});await page.waitForFunction(c=>document.documentElement.dataset.theme===c,color);await layout(mode.name+' '+color+' plans');if(mode.name==='portrait')await page.screenshot({path:output+'/plans-'+color+'.png'});
    await page.getByRole('button',{name:'更换计划'}).click();await layout(mode.name+' '+color+' templates');await dialog(page).getByRole('button',{name:'无氧计划',exact:true}).click();await dialog(page).getByRole('button',{name:/无氧适应/}).click();await layout(mode.name+' '+color+' preview');await dialog(page).getByRole('button',{name:'关闭采用计划'}).click();
    await dialog(page).getByRole('button',{name:'自定义计划',exact:true}).click();await dialog(page).getByLabel('训练类型').selectOption('anaerobic');await dialog(page).getByText('热身与放松',{exact:true}).click();await layout(mode.name+' '+color+' custom');if(mode.name==='portrait')await page.screenshot({path:output+'/custom-'+color+'.png',fullPage:true});await dialog(page).getByRole('button',{name:'关闭自定义计划'}).click();
    await page.getByRole('button',{name:'进入跟练',exact:true}).click();await layout(mode.name+' '+color+' follow');assert.equal(await dialog(page).getByRole('img').count(),0);assert.equal(await dialog(page).locator('.effort-value').innerText(),'3–5');assert.equal(await dialog(page).locator('.effort-max').innerText(),'/ 16');const hierarchy=await dialog(page).evaluate(e=>{const size=c=>parseFloat(getComputedStyle(e.querySelector(c)).fontSize);return {effort:size('.effort-value'),next:size('.next-kind'),duration:size('.next-duration'),cue:size('.effort-cue'),cueWeight:getComputedStyle(e.querySelector('.effort-cue')).fontWeight};});assert.ok(hierarchy.effort>=hierarchy.cue*2&&hierarchy.next>hierarchy.cue&&hierarchy.duration>hierarchy.cue);assert.equal(hierarchy.cueWeight,'400');for(const label of ['开始跟练','结束跟练'])assert.ok((await dialog(page).getByRole('button',{name:label,exact:true}).boundingBox()).height>=64);if(mode.name==='portrait')await page.screenshot({path:output+'/follow-'+color+'.png'});await dialog(page).getByRole('button',{name:'关闭跟练',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'丢弃本次',exact:true}).click();await page.getByRole('button',{name:'进入跟练',exact:true}).waitFor();results.push(mode.name+' '+color+'：计划、模板、自定义与跟练布局');
  }
  await page.setViewportSize({width:420,height:912});await page.evaluate(()=>{for(const side of ['top','bottom','left','right'])document.documentElement.style.setProperty('--safe-'+side,'0px');document.documentElement.style.fontSize='34px';});await layout('200% plans');await page.getByRole('button',{name:'更换计划'}).click();await layout('200% templates');await dialog(page).getByRole('button',{name:'自定义计划',exact:true}).click();await layout('200% custom');await dialog(page).getByRole('button',{name:'关闭自定义计划'}).click();await page.getByRole('button',{name:'进入跟练'}).click();await layout('200% follow');await dialog(page).getByRole('button',{name:'关闭跟练',exact:true}).click();results.push('200% 字体放大，无横向溢出，所有主要操作可滚动访问');
  await page.waitForFunction(()=>!document.querySelector('dialog[open]'));await page.evaluate(()=>document.documentElement.style.removeProperty('font-size'));await page.getByRole('button',{name:'打开设置'}).focus();await page.keyboard.press('Enter');await page.keyboard.press('Escape');await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='打开设置');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'打开设置');results.push('原生模态键盘与焦点恢复');
  assert.deepEqual(errors,[]);await fs.writeFile(output+'/report.json',JSON.stringify({url:appURL,device:actual,results,pageErrors:errors,limitation:'Chromium 参数模拟，未运行真实 iOS Safari'},null,2));console.log(JSON.stringify({passed:results.length,results},null,2));
}catch(error){await page.screenshot({path:output+'/failure.png',fullPage:true});throw error;}finally{await browser.close();}
