import {useState} from 'react';
import {blankMetrics,metricsFromInput} from '../../application/service.ts';
import {newEntity,type Workout} from '../../domain/types.ts';
import {formatTime} from '../../domain/session.ts';
import {weekStats} from '../../domain/plans.ts';
import {useApp} from '../context.ts';
import {Sheet} from '../components/Sheet.tsx';
import {Icon} from '../components/Icon.tsx';
import {Row,Section,Empty,Notice} from '../components/shared.tsx';
import {initialFeedback,RecordFields} from '../components/RecordFields.tsx';
export function History(){const {data}=useApp(),[limit,setLimit]=useState(20),[detail,setDetail]=useState<Workout|null>(null),[edit,setEdit]=useState<Workout|'new'|null>(null);
  const records=[...data.workouts].sort((a,b)=>b.startedAt.localeCompare(a.startedAt));const stats=weekStats(data.workouts,data.profile?.timeZone||Intl.DateTimeFormat().resolvedOptions().timeZone);
  return <><div className="summary-inline"><span>本周 <strong>{stats.count}</strong> 次</span><span>合计 <strong>{stats.minutes}</strong> 分钟</span><button className="text-button" onClick={()=>setEdit('new')}><Icon name="plus" size={18}/>补录训练</button></div>{records.length?<Section title="每一次积累"><div className="group">{records.slice(0,limit).map(w=><Row key={w.id} icon={w.completionStatus==='completed'?'check':'clock'} title={w.title} subtitle={`${new Date(w.startedAt).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:data.profile?.timeZone})} · ${w.captureSource==='guided'?'跟练计时':'手动记录'} · ${w.completionStatus==='completed'?'已完成':'提前结束'}`} right={formatTime(w.activeDurationSeconds)} onClick={()=>setDetail(w)}/>)}</div>{records.length>limit&&<button className="secondary full" onClick={()=>setLimit(limit+20)}>加载更多记录</button>}</Section>:<Empty title="还没有训练记录" description="完成跟练或补录后，会显示在这里。"/>}{detail&&<RecordDetail record={detail} onClose={()=>setDetail(null)} onEdit={()=>{setEdit(detail);setDetail(null);}}/>}{edit&&<RecordEditor record={edit==='new'?undefined:edit} onClose={()=>setEdit(null)}/>}</>;
}
function RecordDetail({record:w,onClose,onEdit}:{record:Workout;onClose:()=>void;onEdit:()=>void}) {const {perform,service,busy}=useApp(),[confirm,setConfirm]=useState(false);return <Sheet title="训练记录" onClose={onClose}><span className="badge">{w.captureSource==='guided'?'跟练计时':'手动记录'} · {w.completionStatus==='completed'?'已完成':'提前结束'}</span><h3 className="detail-lead">{w.title}</h3><div className="group"><Row title="总训练时长" subtitle="含热身、恢复和放松；排除暂停" right={formatTime(w.activeDurationSeconds)}/><Row title="工作段时长" right={formatTime(w.workDurationSeconds)}/>{Object.entries({distance:'距离',pace:'整次平均配速',spm:'平均划频',power:'平均功率',calories:'设备热量读数'}).map(([key,label])=><Row key={key} title={label} subtitle={w.metrics[key]?.source==='derived'?'依据整次时长和距离计算':w.metrics[key]?'设备读数手填':undefined} right={w.metrics[key]?key==='pace'?`${formatTime(w.metrics[key]!.value)} / 500米`:`${w.metrics[key]!.value} ${w.metrics[key]!.unit}`:'未记录'}/>)}<Row title="用力程度" right={`${w.feedback.rpe} / 10`}/><Row title="动作自评" right={w.feedback.technique==='stable'?'感觉稳定':'需要练习'}/><Row title="训练后感觉" right={w.feedback.feeling==='good'?'良好':'疲劳'}/></div>{w.feedback.discomfort&&<Notice tone="warning">这次记录了不适。先休息，根据实际情况获得专业建议。</Notice>}{w.feedback.note&&<p className="record-note">{w.feedback.note}</p>}<button className="secondary full" onClick={onEdit}>编辑读数与感受</button>{confirm?<Notice tone="warning">删除后不能撤销，关联计划将恢复为待训练。<div className="button-pair"><button className="secondary" onClick={()=>setConfirm(false)}>保留记录</button><button className="danger-button" disabled={busy} onClick={()=>void perform(()=>service.deleteWorkout(w.id),'记录已删除。').then(ok=>{if(ok)onClose();})}>删除这条记录</button></div></Notice>:<button className="text-button danger full" onClick={()=>setConfirm(true)}>删除记录</button>}</Sheet>;}
function RecordEditor({record,onClose}:{record?:Workout;onClose:()=>void}){
  const {service,perform,busy}=useApp();const [identity]=useState(()=>record||{...newEntity(),sessionId:crypto.randomUUID()});
  const [title,setTitle]=useState(record?.title||'自由划行'),[minutes,setMinutes]=useState(String((record?.activeDurationSeconds||900)/60)),[feedback,setFeedback]=useState(record?.feedback||initialFeedback()),[metrics,setMetrics]=useState(()=>{const values=blankMetrics();for(const key of Object.keys(values) as (keyof typeof values)[])if(record?.metrics[key])values[key]=String(record.metrics[key]!.value);return values;});
  const [date,setDate]=useState(()=>{const d=new Date(record?.startedAt||Date.now());return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);});
  return <Sheet title={record?'编辑训练记录':'补录训练'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();void perform(async()=>{
    const seconds=record?.captureSource==='guided'?record.activeDurationSeconds:Number(minutes)*60,start=new Date(date).toISOString();
    const value:Workout={...identity,updatedAt:new Date().toISOString(),version:record?record.version+1:1,title,startedAt:record?.startedAt||start,endedAt:record?.captureSource==='guided'?record.endedAt:new Date(Date.parse(record?.startedAt||start)+seconds*1000).toISOString(),captureSource:record?.captureSource||'manual-entry',completionStatus:record?.completionStatus||'completed',activeDurationSeconds:seconds,workDurationSeconds:record?.workDurationSeconds||0,course:record?.course,scheduledId:record?.scheduledId,stageResults:record?.stageResults||[],feedback,metrics:metricsFromInput(metrics,seconds)};
    await service.saveManual(value,record?.version);
  },'记录已保存。').then(ok=>{if(ok)onClose();});}}><label>训练名称<input value={title} required maxLength={60} onChange={e=>setTitle(e.target.value)}/></label><label>开始时间<input type="datetime-local" value={date} required disabled={!!record} onChange={e=>setDate(e.target.value)}/></label><label>总训练时长（分钟）<input type="number" min="0.017" max="360" step="any" inputMode="decimal" required disabled={record?.captureSource==='guided'} value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><RecordFields {...{feedback,setFeedback,metrics,setMetrics}}/><button className="primary" disabled={busy}>保存记录</button></form></Sheet>;
}
