import {useState} from 'react';
import type {Scheduled} from '../../domain/types.ts';
import {planMode,planWeeks} from '../../domain/focused-plans.ts';
import {addDays} from '../../domain/plans.ts';
import {modeNames} from '../../content/presets.ts';
import {useApp} from '../context.ts';
import {Sheet} from '../components/Sheet.tsx';
import {Icon} from '../components/Icon.tsx';
import {Section,Notice} from '../components/shared.tsx';
import {PlanLibrary} from './PlanLibrary.tsx';
import {PlanEditor} from './PlanEditor.tsx';
export function Plans(){
  const {data,service,perform,busy,openSession}=useApp();
  const plan=data.plans.find(p=>p.status==='active');
  const [library,setLibrary]=useState(false),[editor,setEditor]=useState(false),[viewWeek,setViewWeek]=useState<{id:string;week:number}|null>(null),[adjust,setAdjust]=useState<Scheduled|null>(null),[date,setDate]=useState(''),[confirm,setConfirm]=useState<Scheduled|null>(null),[ready,setReady]=useState(false);
  const items=plan?data.scheduled.filter(s=>s.planId===plan.id):[],next=items.filter(s=>s.status==='planned').sort((a,b)=>a.week-b.week||a.localDate.localeCompare(b.localDate))[0];
  const week=plan&&viewWeek?.id===plan.id?Math.min(viewWeek.week,planWeeks(plan)-1):plan?.week||0;
  const start=(s:Scheduled,confirmed=false)=>void perform(async()=>{const draft=await service.beginScheduled(s.id,confirmed);openSession(draft);}).then(ok=>{if(ok){setConfirm(null);}});
  const choose=(s:Scheduled)=>{if(s.course.category==='interval'){setReady(false);setConfirm(s);}else start(s);};
  const done=items.filter(s=>s.status==='completed').length;
  return <>
    {data.draft&&<div className="draft-card"><div><strong>上次跟练尚未结束</strong><p className="caption">{data.draft.course.title}</p></div><button className="primary" disabled={busy} onClick={()=>void perform(async()=>{const draft=await service.claim();openSession(draft);})}>继续跟练</button><button className="text-button danger" disabled={busy} onClick={()=>{if(window.confirm('丢弃这次尚未完成的跟练？已保存的数据会保留。'))void perform(()=>service.discardDraft());}}>丢弃本次</button></div>}
    {plan?<>
      <section className="plan-card"><span className="badge">{modeNames[planMode(plan)]} · {planWeeks(plan)} 周</span><h2>{plan.title}</h2><p className="caption">已完成 {done} / {plan.training?items.length:Math.max(items.length,planWeeks(plan)*(data.profile?.weeklyDays||3))} 次</p><svg className="progress-track" viewBox="0 0 100 5" preserveAspectRatio="none" role="progressbar" aria-label="计划进度" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(done/Math.max(1,plan.training?items.length:Math.max(items.length,planWeeks(plan)*(data.profile?.weeklyDays||3)))*100)}><rect width="100" height="5" rx="2.5" fill="var(--line)"/><rect width={Math.min(100,done/Math.max(1,plan.training?items.length:Math.max(items.length,planWeeks(plan)*(data.profile?.weeklyDays||3)))*100)} height="5" rx="2.5" fill="var(--accent)"/></svg>{next&&!data.draft&&<div className="next-workout"><div><strong>{next.course.title===plan.title?'下一次跟练':next.course.title}</strong><p className="caption">{next.localDate} · {Math.round(next.course.plannedDurationSeconds/60)} 分钟</p></div><button className="primary" disabled={busy} onClick={()=>choose(next)}><Icon name="play" size={20}/>进入跟练</button></div>}</section>
      <Section title="训练日程"><div className="week-picker"><button className="icon-button" aria-label="上一周" disabled={week===0} onClick={()=>setViewWeek({id:plan.id,week:week-1})}><Icon name="back"/></button><label className="week-label"><span className="sr-only">查看周次</span><select aria-label="查看周次" value={week} onChange={e=>setViewWeek({id:plan.id,week:Number(e.target.value)})}>{Array.from({length:planWeeks(plan)},(_,i)=><option key={i} value={i}>第 {i+1} 周</option>)}</select></label><button className="icon-button" aria-label="下一周" disabled={week===planWeeks(plan)-1} onClick={()=>setViewWeek({id:plan.id,week:week+1})}><Icon name="chevron"/></button></div><div className="group">{items.filter(s=>s.week===week).sort((a,b)=>a.localDate.localeCompare(b.localDate)).map(s=><div className="schedule-row" key={s.id}><button className="list-row" disabled={s.status!=='planned'||!!data.draft||busy} onClick={()=>choose(s)}><span className="row-copy"><strong>{s.course.title}</strong><small>{s.localDate} · {Math.round(s.course.plannedDurationSeconds/60)} 分钟</small></span><span className="row-value">{s.status==='completed'?'已完成':s.status==='skipped'?'已跳过':'跟练'}</span></button>{s.status!=='completed'&&<button className="icon-button" aria-label={'调整'+s.course.title+' '+s.localDate} disabled={busy||!!data.draft} onClick={()=>{setAdjust(s);setDate(s.localDate);}}><Icon name="settings" size={20}/></button>}</div>)}</div>{!items.some(s=>s.week===week)&&<p className="caption">完成当前周后生成这一周的安排。</p>}</Section>
      <div className="plan-actions"><button className="secondary" disabled={busy||!!data.draft} onClick={()=>setLibrary(true)}>更换计划</button>{plan.training?.custom&&<button className="secondary" disabled={busy||!!data.draft} onClick={()=>setEditor(true)}>编辑计划</button>}</div>
    </>:<><Section title={data.plans.some(p=>p.status==='completed')?'本轮已结束 · 选择下一轮':'选择训练计划'}><PlanLibrary onFinish={()=>setViewWeek(null)}/></Section></>}
    {library&&<Sheet title="选择计划" onClose={()=>setLibrary(false)}><PlanLibrary onFinish={()=>{setLibrary(false);setViewWeek(null);}}/></Sheet>}
    {editor&&plan&&<PlanEditor existing={plan} onClose={()=>setEditor(false)}/>}
    {confirm&&<Sheet title="无氧跟练" onClose={()=>setConfirm(null)}><h3>{confirm.course.title}</h3><p className="caption">短工作段后充分恢复。出现不适请停止。</p><label className="check-row"><input type="checkbox" checked={ready} onChange={e=>setReady(e.target.checked)}/><span>我已有规律划船基础，今天无疲劳或不适。</span></label><button className="primary" disabled={!ready||busy||!!data.draft} onClick={()=>start(confirm,true)}>进入跟练</button></Sheet>}
    {adjust&&plan&&<Sheet title="调整日程" onClose={()=>setAdjust(null)}><h3>{adjust.course.title}</h3>{adjust.status==='planned'?<><label>训练日期<input type="date" value={date} min={plan.training?addDays(plan.startDate,adjust.week*7):undefined} max={plan.training?addDays(plan.startDate,adjust.week*7+6):undefined} onChange={e=>setDate(e.target.value)}/></label><button className="primary" disabled={busy} onClick={()=>void perform(()=>service.adjustFocusedSession(adjust.id,'move',date)).then(ok=>{if(ok)setAdjust(null);})}>保存日期</button><button className="text-button full" disabled={busy} onClick={()=>void perform(()=>service.adjustFocusedSession(adjust.id,'skip')).then(ok=>{if(ok)setAdjust(null);})}>跳过这次</button></>:<button className="primary" disabled={busy} onClick={()=>void perform(()=>service.adjustFocusedSession(adjust.id,'restore')).then(ok=>{if(ok)setAdjust(null);})}>恢复这次训练</button>}{adjust.course.category==='interval'&&<Notice>无氧课程之间需保留恢复时间。</Notice>}</Sheet>}
  </>;
}
