import {useState} from 'react';
import {newEntity,APP_VERSION,CONTENT_VERSION,type Backup,type Profile} from '../../domain/types.ts';
import {parseBackup} from '../../domain/validation.ts';
import {importPreview} from '../../application/service.ts';
import {downloadJson} from '../../adapters/download.ts';
import {localDate} from '../../domain/plans.ts';
import {useApp} from '../context.ts';
import {Row,Section,Notice} from '../components/shared.tsx';
import {Sheet} from '../components/Sheet.tsx';
import {Icon} from '../components/Icon.tsx';
export function defaultProfile():Profile {return {...newEntity('profile'),experience:'new',goal:'technique',weeklyDays:3,availableMinutes:20,machine:'通用家用划船机',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,sound:false};}
export function ProfileForm({onClose,first=false}:{onClose:()=>void;first?:boolean}) {
  const {data,service,perform,busy}=useApp(),[profile,setProfile]=useState(data.profile||defaultProfile());
  return <Sheet title={first?'安排自己的训练节奏':'训练偏好'} onClose={onClose}><p>从轻松的动作练习开始。只需选择经验、目标和可用时间。</p><form onSubmit={e=>{e.preventDefault();const next={...profile,updatedAt:new Date().toISOString(),version:(data.profile?.version||0)+1};void perform(()=>service.saveProfile(next),'训练偏好已保存。').then(ok=>{if(ok)onClose();});}}><label>划船经验<select value={profile.experience} onChange={e=>setProfile({...profile,experience:e.target.value as Profile['experience']})}><option value="new">刚开始</option><option value="basic">能连续完成轻松训练</option><option value="regular">已有规律训练经验</option></select></label><label>主要目标<select value={profile.goal} onChange={e=>setProfile({...profile,goal:e.target.value as Profile['goal']})}><option value="technique">掌握动作</option><option value="habit">建立运动习惯</option><option value="aerobic">有氧耐力</option><option value="interval">高强度表现</option></select></label><div className="form-grid"><label>每周训练<select value={profile.weeklyDays} onChange={e=>setProfile({...profile,weeklyDays:Number(e.target.value)})}>{[2,3,4].map(n=><option key={n} value={n}>{n} 次</option>)}</select></label><label>单次可用时间<select value={profile.availableMinutes} onChange={e=>setProfile({...profile,availableMinutes:Number(e.target.value)})}>{[15,20,30,45].map(n=><option key={n} value={n}>{n} 分钟</option>)}</select></label></div><label>设备类别<select value={profile.machine} onChange={e=>setProfile({...profile,machine:e.target.value})}>{['通用家用划船机','风阻划船机','水阻划船机','磁阻划船机','复合阻力划船机'].map(name=><option key={name}>{name}</option>)}</select></label><Notice>每个品牌的阻力和读数不同，设置以说明书为准。高强度课程需先具备基础，不会因为选择目标就自动开放。</Notice><button className="primary" disabled={busy}>保存训练偏好</button>{first&&<button className="text-button full" type="button" disabled={busy} onClick={()=>void perform(()=>service.saveProfile(defaultProfile())).then(ok=>{if(ok)onClose();})}>先用新手默认设置</button>}</form></Sheet>;
}
export function Settings({onClose}:{onClose:()=>void}){
  const {data,service,perform,busy,theme,setTheme,themeError,notify,offlineReady,updateAvailable,applyUpdate}=useApp(),[profile,setProfile]=useState(false),[preview,setPreview]=useState<{backup:Backup;revision:number}|null>(null);
  const readFile=async(file?:File)=>{if(!file)return;try{if(!/\.json$/i.test(file.name)||file.size>10*1024*1024)throw new Error('请选择 10MB 以内的 JSON 备份。');const backup=parseBackup(await file.text());const latest=await service.repository.read();setPreview({backup,revision:latest.revision});}catch(error){notify(error instanceof Error?error.message:'文件读取失败，请重新选择。');}};
  return <Sheet title="设置" onClose={onClose}>
    <Section title="训练"><div className="group"><Row icon="row" title="训练偏好" subtitle="经验、目标与时间安排" onClick={()=>setProfile(true)}/><label className="switch-row"><span>阶段提示音</span><input type="checkbox" role="switch" checked={data.profile?.sound||false} disabled={busy} onChange={e=>{const p=data.profile||defaultProfile();void perform(()=>service.saveProfile({...p,sound:e.target.checked,version:p.version+1,updatedAt:new Date().toISOString()}));}}/></label></div></Section>
    <Section title="外观"><div className="segmented" role="group" aria-label="外观模式">{(['system','light','dark'] as const).map(t=><button key={t} aria-pressed={theme===t} className={theme===t?'selected':''} onClick={()=>setTheme(t)}>{t==='system'?'跟随系统':t==='light'?'浅色':'深色'}</button>)}</div>{themeError&&<Notice>{themeError}</Notice>}</Section>
    <Section title="本机数据"><div className="group"><Row icon="download" title="导出 JSON 备份" subtitle={data.lastBackupAt?`上次导出 ${new Date(data.lastBackupAt).toLocaleDateString('zh-CN')}`:'保存一份本机记录'} onClick={()=>void perform(async()=>{downloadJson(await service.backup(),`home-rower-backup-${localDate()}.json`);await service.markBackup();},'已发起备份下载，请确认文件已保存。')}/><label className="list-row file-row"><span className="row-icon"><Icon name="upload" size={21}/></span><span className="row-copy"><strong>选择备份文件</strong><small>校验和预览后再确认导入</small></span><input type="file" accept=".json,application/json" aria-label="选择 JSON 备份文件" disabled={busy||!service.repository.persistent} onChange={e=>{void readFile(e.target.files?.[0]);e.target.value='';}}/></label></div>{data.draft&&<p className="footnote">导入前需先保存或丢弃当前草稿。</p>}</Section>
    <Section title="安装与离线"><div className="group"><Row icon="shield" title={offlineReady?'离线资源已就绪':'离线资源尚未就绪'} subtitle="首次联网打开正式构建后准备离线资源"/><Row icon="upload" title="添加到 iPhone 主屏幕" subtitle="在 Safari 中打开 → 分享 → 添加到主屏幕"/></div>{updateAvailable&&<button className="secondary full" disabled={!!data.draft||busy} onClick={()=>void applyUpdate()}>更新应用版本</button>}</Section>
    <details className="disclosure"><summary>关于与数据说明</summary><p className="caption">划船机 {APP_VERSION} · 内容 {CONTENT_VERSION} 已确认</p><p className="caption">记录保存在本机，备份文件未加密，请妥善保管。无账号、设备连接或云同步。iOS 真机验收尚未完成。</p></details>
    {profile&&<ProfileForm onClose={()=>setProfile(false)}/>}
    {preview&&<Sheet title="导入预览" onClose={()=>setPreview(null)}><Notice>采用合并方式；重复与冲突保留本机内容，不覆盖已有记录。预览后其他窗口有修改时需重新选择文件。</Notice><div className="group"><Row title="备份训练记录" right={String(preview.backup.counts.workouts)}/><Row title="新增记录" right={String(importPreview(preview.backup,data).added)}/><Row title="相同记录" right={String(importPreview(preview.backup,data).duplicates)}/><Row title="冲突 · 保留本机" right={String(importPreview(preview.backup,data).conflicts)}/><Row title="计划 / 日程 / 学习进度" right={`${preview.backup.counts.plans} / ${preview.backup.counts.scheduled} / ${preview.backup.counts.lessons}`}/><Row title="暂停草稿" right={preview.backup.data.draft?'有':'无'}/></div><button className="primary" disabled={busy||!!data.draft} onClick={()=>void perform(async()=>{await service.importBackup(preview.backup,preview.revision);const verified=await service.repository.read();if(verified.schemaVersion!==1)throw new Error('导入后核验失败，请保留原备份。');},'备份已合并，数据核验完成。').then(ok=>{if(ok)setPreview(null);})}>确认合并导入</button></Sheet>}
  </Sheet>;
}
