import {useState} from 'react';
import {courses,goalNames,planTemplates} from '../../content/courses.ts';
import {canAdvancePlan,previewPlan,suggestedTemplate} from '../../domain/plans.ts';
import type {Goal} from '../../domain/types.ts';
import {useApp} from '../context.ts';
import {Row,Section,Empty} from '../components/shared.tsx';
import {Sheet} from '../components/Sheet.tsx';
export function Training(){
  const {data,perform,service,openCourse,notify,busy}=useApp();
  const [filter,setFilter]=useState<Goal|'all'|'recovery'>('all'),[duration,setDuration]=useState(60),[level,setLevel]=useState('all'),[tab,setTab]=useState<'courses'|'plans'>('courses'),[preview,setPreview]=useState<ReturnType<typeof previewPlan>|null>(null),[revision,setRevision]=useState(0),[move,setMove]=useState<{id:string;date:string}|null>(null);
  const shown=courses.filter(c=>(filter==='all'||c.category===filter)&&c.plannedDurationSeconds<=duration*60&&(level==='all'||c.level===level));
  const active=data.plans.find(p=>p.status==='active'),sessions=data.scheduled.filter(s=>s.planId===active?.id&&s.week===active?.week).sort((a,b)=>a.localDate.localeCompare(b.localDate)),filtersActive=filter!=='all'||duration!==60||level!=='all';
  return <>
    <div className="segmented" role="group" aria-label="训练内容">{(['courses','plans'] as const).map(t=><button key={t} aria-pressed={tab===t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t==='courses'?'课程':'四周计划'}</button>)}</div>
    {tab==='courses'?<>
      <details className="disclosure course-filters"><summary>{filtersActive?'筛选课程 · '+shown.length+' 节':'筛选课程'}</summary><div className="filter-chips" role="group" aria-label="训练目标">{(['all','technique','aerobic','interval','recovery'] as const).map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f==='all'?'全部':goalNames[f]}</button>)}</div><div className="filter-row"><label>可用时间<select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={60}>不限时长</option><option value={15}>15 分钟以内</option><option value={20}>20 分钟以内</option><option value={30}>30 分钟以内</option></select></label><label>适用经验<select value={level} onChange={e=>setLevel(e.target.value)}><option value="all">全部经验</option><option value="new">新手</option><option value="basic">有基础</option><option value="regular">规律训练</option></select></label></div>{filtersActive&&<button className="text-button" onClick={()=>{setFilter('all');setDuration(60);setLevel('all');}}>清除筛选</button>}</details>
      <div className="group">{shown.map(c=><Row key={c.id} icon={c.category==='technique'?'row':c.category==='interval'?'train':c.category==='recovery'?'heart':'clock'} title={c.title} subtitle={goalNames[c.category]+' · '+(c.level==='new'?'新手':c.level==='basic'?'有基础':'规律训练')} right={c.plannedDurationSeconds/60+' 分钟'} onClick={()=>openCourse(c)}/>)}</div>{!shown.length&&<Empty title="没有匹配的课程" description="调整时长或清除筛选。"/>}
    </>:<>
      {active&&<Section title={'第 '+(active.week+1)+' 周'}><div className="group">{sessions.map(s=><div className="schedule-item" key={s.id}><Row title={s.course.title} subtitle={s.localDate+' · '+s.course.plannedDurationSeconds/60+' 分钟'} right={s.status==='completed'?'已完成':s.status==='skipped'?'已跳过':'待训练'} onClick={s.status==='planned'?()=>openCourse(s.course,s.id):undefined}/>{s.status==='planned'&&<details className="disclosure schedule-disclosure"><summary>调整安排</summary><div className="schedule-actions"><button className="text-button" onClick={()=>setMove({id:s.id,date:s.localDate})}>调整日期</button><button className="text-button" onClick={()=>void perform(()=>service.adjustSchedule(s.id,'skip'),'已跳过本节。')}>跳过本节</button></div></details>}</div>)}</div><details className="disclosure"><summary>计划进度</summary><div className="button-pair"><button className="secondary" disabled={busy} onClick={()=>void perform(()=>service.advancePlan(active.id,true),'已重新安排当前周。')}>重复当前周</button><button className="secondary" disabled={busy||!canAdvancePlan(active,data)} onClick={()=>void perform(()=>service.advancePlan(active.id),'计划已更新。')}>{active.week===3?'完成计划':'进入下一周'}</button></div><p className="caption">至少完成两节动作稳定、无不适的课程后，可主动进入下一周。</p></details></Section>}
      <Section title={active?'其他计划':'四周计划'}><div className="group">{planTemplates.map(p=><Row key={p.id} icon={p.id==='P03'?'train':'history'} title={p.title} subtitle={p.subtitle} right={p.id===suggestedTemplate(data)?'推荐':undefined} onClick={()=>{try{const generated=previewPlan(p.id,data);setRevision(data.revision);setPreview(generated);}catch(error){notify(error instanceof Error?error.message:'请先填写偏好。');}}}/>)}</div></Section>
    </>}
    {preview&&<Sheet title="计划预览" onClose={()=>setPreview(null)}><h3>{preview.plan.title}</h3><div className="group">{preview.sessions.map(s=><Row key={s.id} title={s.course.title} subtitle={s.localDate} right={s.course.plannedDurationSeconds/60+' 分钟'}/>)}</div><details className="disclosure"><summary>安排说明</summary><p>{preview.plan.reason}</p><p className="caption">第一周安排。采用后暂停原计划，保留历史。</p></details><button className="primary" disabled={busy} onClick={()=>void perform(()=>service.usePlan(preview.plan.templateId,revision),'计划已保存。').then(ok=>{if(ok)setPreview(null);})}>采用这个计划</button></Sheet>}
    {move&&<Sheet title="调整课程日期" onClose={()=>setMove(null)}><form onSubmit={e=>{e.preventDefault();void perform(()=>service.adjustSchedule(move.id,'move',move.date),'日期已更新。').then(ok=>{if(ok)setMove(null);});}}><label>训练日期<input type="date" required value={move.date} onChange={e=>setMove({...move,date:e.target.value})}/></label><button className="primary" disabled={busy}>保存日期</button></form></Sheet>}
  </>;
}
